<a href="https://colab.research.google.com/github/deepmalasrivastava/Playstore_analysis/blob/main/PlayStoreDataReviewAnalysis_deepmala.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Importing Required Pakages***

In [ ]:
# Importing libraries
import pandas as pd               # for data manipulation
import numpy as np                # for mathemathical operations and linear algebra
import matplotlib.pyplot as plt   # for data visualization
import seaborn as sns             # for data visualization
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

# **Load PlayStore Data and User Review Data File**

In [ ]:
playstore_df= pd.read_csv('/content/Play Store Data.csv')
user_reviews_df= pd.read_csv('/content/User Reviews.csv')

# **Load first & last 10 lines  from both files**

In [ ]:
playstore_df.head(10) #for Loading first 10 rows of playstore dataframe

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
5,Paper flowers instructions,ART_AND_DESIGN,4.4,167,5.6M,"50,000+",Free,0,Everyone,Art & Design,"March 26, 2017",1.0,2.3 and up
6,Smoke Effect Photo Maker - Smoke Editor,ART_AND_DESIGN,3.8,178,19M,"50,000+",Free,0,Everyone,Art & Design,"April 26, 2018",1.1,4.0.3 and up
7,Infinite Painter,ART_AND_DESIGN,4.1,36815,29M,"1,000,000+",Free,0,Everyone,Art & Design,"June 14, 2018",6.1.61.1,4.2 and up
8,Garden Coloring Book,ART_AND_DESIGN,4.4,13791,33M,"1,000,000+",Free,0,Everyone,Art & Design,"September 20, 2017",2.9.2,3.0 and up
9,Kids Paint Free - Drawing Fun,ART_AND_DESIGN,4.7,121,3.1M,"10,000+",Free,0,Everyone,Art & Design;Creativity,"July 3, 2018",2.8,4.0.3 and up

In [ ]:
playstore_df.tail(10) #for loading 10 last rows of Play Store dataframe

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10831,payermonstationnement.fr,MAPS_AND_NAVIGATION,NaN,38,9.8M,"5,000+",Free,0,Everyone,Maps & Navigation,"June 13, 2018",2.0.148.0,4.0 and up
10832,FR Tides,WEATHER,3.8,1195,582k,"100,000+",Free,0,Everyone,Weather,"February 16, 2014",6.0,2.1 and up
10833,Chemin (fr),BOOKS_AND_REFERENCE,4.8,44,619k,"1,000+",Free,0,Everyone,Books & Reference,"March 23, 2014",0.8,2.2 and up
10834,FR Calculator,FAMILY,4.0,7,2.6M,500+,Free,0,Everyone,Education,"June 18, 2017",1.0.0,4.1 and up
10835,FR Forms,BUSINESS,NaN,0,9.6M,10+,Free,0,Everyone,Business,"September 29, 2016",1.1.5,4.0 and up
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [ ]:
user_reviews_df.head(10) #for Loading first 10 rows of User Reviews dataframe

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000
5,10 Best Foods for You,Best way,Positive,1.00,0.300000
6,10 Best Foods for You,Amazing,Positive,0.60,0.900000
7,10 Best Foods for You,NaN,NaN,NaN,NaN
8,10 Best Foods for You,"Looking forward app,",Neutral,0.00,0.000000
9,10 Best Foods for You,It helpful site ! It help foods get !,Neutral,0.00,0.000000

In [ ]:
user_reviews_df.tail(10) #for Loading last 10 rows of User Reviews dataframe

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
64285,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN
64286,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN
64287,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN
64288,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN
64289,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN
64290,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN
64291,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN
64292,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN
64293,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN
64294,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN

**Find Duplicate Data and Remove Duplicates**

In [ ]:
print("Shape of playstore_df DataFrame:",playstore_df.shape) #dataframe playstore shape before removing duplicates 
print("Shape of user_reviews_df DataFrame:",user_reviews_df.shape) #dataframe user review  shape before removing dup

Shape of playstore_df DataFrame: (10841, 13)
Shape of user_reviews_df DataFrame: (64295, 5)

In [ ]:
playstore_df.duplicated().sum()

483

In [ ]:
user_reviews_df.duplicated().sum()

33616

In [ ]:
print("Duplicate entry in playstore_df data:",len(playstore_df[playstore_df.duplicated()])) #total number of duplicates
print("Duplicate entry in user_reviews_df data:",len(user_reviews_df[user_reviews_df.duplicated()]))

Duplicate entry in playstore_df data: 483
Duplicate entry in user_reviews_df data: 33616

In [ ]:
playstore_df.duplicated(keep = 'last') #list of all duplicates values

0        False
1        False
2        False
3        False
4        False
         ...
10836    False
10837    False
10838    False
10839    False
10840    False
Length: 10841, dtype: bool

In [ ]:
duplicate_playstore = playstore_df[playstore_df.duplicated(keep = 'last') ] #list of all duplicates values

In [ ]:
duplicate_playstore

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
164,Ebook Reader,BOOKS_AND_REFERENCE,4.1,85842,37M,"5,000,000+",Free,0,Everyone,Books & Reference,"June 25, 2018",5.0.6,4.0 and up
192,Docs To Go™ Free Office Suite,BUSINESS,4.1,217730,Varies with device,"50,000,000+",Free,0,Everyone,Business,"April 2, 2018",Varies with device,Varies with device
193,Google My Business,BUSINESS,4.4,70991,Varies with device,"5,000,000+",Free,0,Everyone,Business,"July 24, 2018",2.19.0.204537701,4.4 and up
204,Box,BUSINESS,4.2,159872,Varies with device,"10,000,000+",Free,0,Everyone,Business,"July 31, 2018",Varies with device,Varies with device
213,ZOOM Cloud Meetings,BUSINESS,4.4,31614,37M,"10,000,000+",Free,0,Everyone,Business,"July 20, 2018",4.1.28165.0716,4.0 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3787,ABC News - US & World News,NEWS_AND_MAGAZINES,4.0,18976,35M,"1,000,000+",Free,0,Everyone 10+,News & Magazines,"June 6, 2018",3.19.11,5.0 and up
3788,NBC News,NEWS_AND_MAGAZINES,4.1,63020,Varies with device,"5,000,000+",Free,0,Everyone 10+,News & Magazines,"February 13, 2018",Varies with device,Varies with device
3790,USA TODAY,NEWS_AND_MAGAZINES,4.1,49259,Varies with device,"5,000,000+",Free,0,Everyone 10+,News & Magazines,"August 2, 2018",Varies with device,Varies with device
3792,CNN Breaking US & World News,NEWS_AND_MAGAZINES,4.0,293080,25M,"10,000,000+",Free,0,Everyone 10+,News & Magazines,"August 6, 2018",5.17,4.4 and up
3795,Newsroom: News Worth Sharing,NEWS_AND_MAGAZINES,4.2,201737,Varies with device,"10,000,000+",Free,0,Everyone 10+,News & Magazines,"July 3, 2018",Varies with device,Varies with device

In [ ]:
#Remove Duplicates from Main Database
playstore_df1 = playstore_df.drop_duplicates() #remove duplicate and save as new database_df1
playstore_df1.shape #shape after removing duplicates

(10358, 13)

In [ ]:
user_reviews_df.duplicated(keep = 'last')

0         True
1         True
2         True
3         True
4         True
         ...
64290     True
64291     True
64292     True
64293     True
64294    False
Length: 64295, dtype: bool

In [ ]:
duplicate_user_reviews = user_reviews_df[user_reviews_df.duplicated(keep = 'last') ] #list of all duplicates values
duplicate_user_reviews

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000
...,...,...,...,...,...
64289,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN
64290,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN
64291,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN
64292,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN
64293,Houzz Interior Design Ideas,NaN,NaN,NaN,NaN

# **Data Cleaning**

In [ ]:
#Remove Duplicates from Main Database
user_reviews_df1 = user_reviews_df.drop_duplicates() #remove duplicate and save as new DataFrame user_reviews_df1
user_reviews_df.shape #shape after removing duplicates

(64295, 5)

In [ ]:
#removing unnecessary characters and save as playstore_df2
playstore_df2=playstore_df1.replace('[+,$]','',regex=True)
playstore_df2

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,10000,Free,0,Everyone,Art & Design,January 7 2018,1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,500000,Free,0,Everyone,Art & Design;Pretend Play,January 15 2018,2.0.0,4.0.3 and up
2,U Launcher Lite – FREE Live Cool Themes Hide Apps,ART_AND_DESIGN,4.7,87510,8.7M,5000000,Free,0,Everyone,Art & Design,August 1 2018,1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,50000000,Free,0,Teen,Art & Design,June 8 2018,Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,100000,Free,0,Everyone,Art & Design;Creativity,June 20 2018,1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,5000,Free,0,Everyone,Education,July 25 2017,1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100,Free,0,Everyone,Education,July 6 2018,1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,1000,Free,0,Everyone,Medical,January 20 2017,1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,1000,Free,0,Mature 17,Books & Reference,January 19 2015,Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,10000000,Free,0,Everyone,Lifestyle,July 25 2018,Varies with device,Varies with device

In [ ]:
print("Total Rows and Columns in playstore_df2 DataFrame is :",playstore_df2.shape,"\n") #shape function given details of (Rows,Columns)

def playstoreinfo():
    temp_ps = pd.DataFrame(index=playstore_df2.columns)
    temp_ps['DataType'] = playstore_df2.dtypes
    temp_ps["Non-null_Values"] = playstore_df2.count()
    temp_ps['Unique_Values'] = playstore_df2.nunique()
    temp_ps['NaN_Values'] = playstore_df2.isnull().sum()
    temp_ps['NaN_Values_Percentage'] = (temp_ps['NaN_Values']/len(playstore_df2))*100 
    return temp_ps
playstoreinfo()

Total Rows and Columns in playstore_df2 DataFrame is : (10358, 13)

,DataType,Non-null_Values,Unique_Values,NaN_Values,NaN_Values_Percentage
App,object,10358,9653,0,0.000000
Category,object,10358,34,0,0.000000
Rating,float64,8893,40,1465,14.143657
Reviews,object,10358,6002,0,0.000000
Size,object,10358,462,0,0.000000
Installs,object,10358,21,0,0.000000
Type,object,10357,3,1,0.009654
Price,object,10358,93,0,0.000000
Content Rating,object,10357,6,1,0.009654
Genres,object,10358,120,0,0.000000
Last Updated,object,10358,1378,0,0.000000
Current Ver,object,10350,2832,8,0.077235
Android Ver,object,10355,33,3,0.028963

In [ ]:
print("Total Rows and Columns in user_reviews_df1 DataFrame is :",user_reviews_df1.shape,"\n") #shape function given details of (Rows,Columns)

def userReviewsinfo():
    temp_ur = pd.DataFrame(index=user_reviews_df1.columns)
    temp_ur['DataType'] = user_reviews_df1.dtypes
    temp_ur["Non-null_Values"] = user_reviews_df1.count()
    temp_ur['Unique_Values'] = user_reviews_df1.nunique()
    temp_ur['NaN_Values'] = user_reviews_df1.isnull().sum()
    temp_ur['NaN_Values_Percentage'] = (temp_ur['NaN_Values']/len(user_reviews_df1))*100 
    return temp_ur
userReviewsinfo()

Total Rows and Columns in user_reviews_df1 DataFrame is : (30679, 5)

,DataType,Non-null_Values,Unique_Values,NaN_Values,NaN_Values_Percentage
App,object,30679,1074,0,0.000000
Translated_Review,object,29692,27994,987,3.217184
Sentiment,object,29697,3,982,3.200887
Sentiment_Polarity,float64,29697,5410,982,3.200887
Sentiment_Subjectivity,float64,29697,4474,982,3.200887

# **Data Filtering and Each Columns Data Operation**

**Filtering of User Reviews DataFrame**

In [ ]:
#dropped the rows having all null values
user_reviews_df2 = user_reviews_df1.dropna(subset=["Translated_Review"],how="all")
user_reviews_df2.isnull().sum()

App                       0
Translated_Review         0
Sentiment                 0
Sentiment_Polarity        0
Sentiment_Subjectivity    0
dtype: int64

In [ ]:
user_reviews_df2.describe()

       Sentiment_Polarity  Sentiment_Subjectivity
count        29692.000000            29692.000000
mean             0.188868                0.490930
std              0.355694                0.265976
min             -1.000000                0.000000
25%              0.000000                0.350000
50%              0.157143                0.514286
75%              0.422917                0.652703
max              1.000000                1.000000

**App Column Operation**

In [ ]:
duplicate_in_app = playstore_df2[playstore_df2.duplicated('App')]

In [ ]:
playstore_df3 = playstore_df2.drop_duplicates(subset='App',keep='last') 
pd.DataFrame(playstore_df3)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,10000,Free,0,Everyone,Art & Design,January 7 2018,1.0.0,4.0.3 and up
2,U Launcher Lite – FREE Live Cool Themes Hide Apps,ART_AND_DESIGN,4.7,87510,8.7M,5000000,Free,0,Everyone,Art & Design,August 1 2018,1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,50000000,Free,0,Teen,Art & Design,June 8 2018,Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,100000,Free,0,Everyone,Art & Design;Creativity,June 20 2018,1.1,4.4 and up
5,Paper flowers instructions,ART_AND_DESIGN,4.4,167,5.6M,50000,Free,0,Everyone,Art & Design,March 26 2017,1.0,2.3 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,5000,Free,0,Everyone,Education,July 25 2017,1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100,Free,0,Everyone,Education,July 6 2018,1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,1000,Free,0,Everyone,Medical,January 20 2017,1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,1000,Free,0,Mature 17,Books & Reference,January 19 2015,Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,10000000,Free,0,Everyone,Lifestyle,July 25 2018,Varies with device,Varies with device

**Category Column Operation**

In [ ]:
#first checking the values in the Category column.
pd.DataFrame(playstore_df3['Category'].value_counts(ascending=True)).head(10)

                    Category
1.9                        1
BEAUTY                    53
COMICS                    56
PARENTING                 60
ART_AND_DESIGN            61
EVENTS                    64
HOUSE_AND_HOME            73
WEATHER                   79
ENTERTAINMENT             79
LIBRARIES_AND_DEMO        84

In [ ]:
#1.9 look like a outliner so checking data
playstore_df3[playstore_df3['Category'] == '1.9']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,1000,Free,0,Everyone,NaN,February 11 2018,1.0.19,4.0 and up,NaN

In [ ]:
#by mistake dataentry is wrong,so will shift rows from category column and correct it
from copy import deepcopy
missing_entry = deepcopy(playstore_df3.loc[10472])
missing_entry[1:] = missing_entry[1:].shift(periods=1)
playstore_df3.loc[10472] = missing_entry
# remove the temporary variable
del missing_entry

In [ ]:
#crosscheck data with google playstore and update category 
playstore_df3.loc[10472, 'Category'] = 'LIFESTYLE'
playstore_df3.loc[10472]

App               Life Made WI-Fi Touchscreen Photo Frame
Category                                        LIFESTYLE
Rating                                                1.9
Reviews                                              19.0
Size                                                 3.0M
Installs                                             1000
Type                                                 Free
Price                                                   0
Content Rating                                   Everyone
Genres                                                NaN
Last Updated                             February 11 2018
Current Ver                                        1.0.19
Android Ver                                    4.0 and up
Name: 10472, dtype: object

**Rating Column Operation**

In [ ]:
playstore_df3['Rating'].unique()

array([4.1, 4.7, 4.5, 4.3, 4.4, 3.8, 4.2, 4.6, 3.2, 4.0, 4.8, 3.9, 4.9,
       3.6, 3.7, nan, 3.3, 3.4, 3.5, 3.1, 5.0, 2.5, 2.8, 3.0, 2.7, 1.0,
       1.9, 2.9, 2.6, 2.3, 2.2, 1.7, 2.0, 1.8, 2.4, 1.6, 2.1, 1.4, 1.5,
       1.2, '1.9'], dtype=object)

In [ ]:
playstore_df3['Rating'].isnull().sum()

1464

In [ ]:
x=playstore_df3.Rating.median()
playstore_df3.Rating.fillna(x,inplace=True)
playstore_df3.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              1
Price             0
Content Rating    0
Genres            1
Last Updated      0
Current Ver       8
Android Ver       2
dtype: int64

In [ ]:
#'1.9' to convert to datatype float64

playstore_df3['Rating'] = playstore_df3['Rating'].astype('float64')
playstore_df3['Rating'].dtype

dtype('float64')

In [ ]:
playstore_df3['Rating'].unique()

array([4.1, 4.7, 4.5, 4.3, 4.4, 3.8, 4.2, 4.6, 3.2, 4. , 4.8, 3.9, 4.9,
       3.6, 3.7, 3.3, 3.4, 3.5, 3.1, 5. , 2.5, 2.8, 3. , 2.7, 1. , 1.9,
       2.9, 2.6, 2.3, 2.2, 1.7, 2. , 1.8, 2.4, 1.6, 2.1, 1.4, 1.5, 1.2])

**Reviews Column Operation**

In [ ]:
playstore_df3['Reviews'].unique() #Find Unique Values From Reviews Columns

array(['159', '87510', '215644', ..., '603', '1195', '398307'],
      dtype=object)

In [ ]:
playstore_df3['Reviews'] = playstore_df3['Reviews'].astype('int')
playstore_df3['Reviews'].dtype

dtype('int64')

In [ ]:
playstore_df3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9653 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             9653 non-null   object
 1   Category        9653 non-null   object
 2   Rating          9653 non-null   float64
 3   Reviews         9653 non-null   int64
 4   Size            9653 non-null   object
 5   Installs        9653 non-null   object
 6   Type            9652 non-null   object
 7   Price           9653 non-null   object
 8   Content Rating  9653 non-null   object
 9   Genres          9652 non-null   object
 10  Last Updated    9653 non-null   object
 11  Current Ver     9645 non-null   object
 12  Android Ver     9651 non-null   object
dtypes: float64(1), int64(1), object(11)
memory usage: 1.3+ MB

**Installs Column Operation**

In [ ]:
playstore_df3['Installs']=playstore_df3['Installs'].astype('int')
playstore_df3['Installs'].isnull().sum()
playstore_df3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9653 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             9653 non-null   object
 1   Category        9653 non-null   object
 2   Rating          9653 non-null   float64
 3   Reviews         9653 non-null   int64
 4   Size            9653 non-null   object
 5   Installs        9653 non-null   int64
 6   Type            9652 non-null   object
 7   Price           9653 non-null   object
 8   Content Rating  9653 non-null   object
 9   Genres          9652 non-null   object
 10  Last Updated    9653 non-null   object
 11  Current Ver     9645 non-null   object
 12  Android Ver     9651 non-null   object
dtypes: float64(1), int64(2), object(10)
memory usage: 1.3+ MB

**Type Column Operation**

In [ ]:
playstore_df3['Type'].unique() #Find Unique Values From Type Columns

array(['Free', 'Paid', nan], dtype=object)

In [ ]:
playstore_df3[playstore_df3.Type.isnull()] #finding NaN data row

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
9148,Command & Conquer: Rivals,FAMILY,4.3,0,Varies with device,0,NaN,0,Everyone 10,Strategy,June 28 2018,Varies with device,Varies with device

In [ ]:
playstore_df3.loc[9148, 'Type'] = 'Free' #Check with playstore and replace with Free 
playstore_df3.loc[9148]

App               Command & Conquer: Rivals
Category                             FAMILY
Rating                                  4.3
Reviews                                   0
Size                     Varies with device
Installs                                  0
Type                                   Free
Price                                     0
Content Rating                  Everyone 10
Genres                             Strategy
Last Updated                   June 28 2018
Current Ver              Varies with device
Android Ver              Varies with device
Name: 9148, dtype: object

In [ ]:
playstore_df3['Type'].unique() #Find Unique Values From Type Columns

array(['Free', 'Paid'], dtype=object)

**Size Columns Operation**

In [ ]:
playstore_df3['Size'].unique()  #Find Unique Values From Size Columns

array(['19M', '8.7M', '25M', '2.8M', '5.6M', '29M', '33M', '3.1M', '28M',
       '12M', '20M', '21M', '37M', '2.7M', '5.5M', '17M', '39M', '31M',
       '14M', '4.2M', '23M', '6.0M', '6.1M', '4.6M', '9.2M', '5.2M',
       '11M', 'Varies with device', '9.4M', '15M', '10M', '1.2M', '24M',
       '26M', '8.0M', '7.9M', '56M', '57M', '35M', '54M', '201k', '3.6M',
       '5.7M', '8.6M', '2.4M', '27M', '2.5M', '7.0M', '16M', '3.4M',
       '8.9M', '3.9M', '2.9M', '38M', '32M', '5.4M', '18M', '1.1M',
       '2.2M', '4.5M', '9.8M', '52M', '9.0M', '6.7M', '30M', '2.6M',
       '7.1M', '3.7M', '22M', '7.4M', '6.4M', '3.2M', '8.2M', '9.9M',
       '4.9M', '9.5M', '5.0M', '5.9M', '13M', '73M', '6.8M', '3.5M',
       '4.0M', '2.3M', '7.2M', '2.1M', '42M', '7.3M', '9.1M', '55M',
       '23k', '6.5M', '1.5M', '7.5M', '51M', '41M', '48M', '8.5M', '46M',
       '8.3M', '4.3M', '4.7M', '3.3M', '40M', '7.8M', '8.8M', '6.6M',
       '5.1M', '61M', '8.4M', '118k', '44M', '695k', '1.6M', '18k', '53M',
       '6.2M', '3.0M', '5.8M', '3.8M', '9.6M', '45M', '63M', '49M', '77M',
       '4.4M', '4.8M', '70M', '6.9M', '9.3M', '10.0M', '8.1M', '36M',
       '84M', '97M', '2.0M', '1.9M', '5.3M', '47M', '556k', '526k', '76M',
       '1.8M', '7.6M', '9.7M', '78M', '72M', '43M', '7.7M', '6.3M',
       '334k', '1.4M', '34M', '93M', '65M', '100M', '50M', '68M', '79M',
       '64M', '67M', '60M', '59M', '94M', '58M', '232k', '99M', '624k',
       '95M', '8.5k', '41k', '292k', '11k', '80M', '1.7M', '69M', '71M',
       '62M', '98M', '85M', '86M', '82M', '81M', '96M', '91M', '83M',
       '87M', '66M', '75M', '92M', '704k', '862k', '899k', '378k', '266k',
       '375k', '74M', '1.3M', '975k', '980k', '4.1M', '89M', '88M',
       '696k', '544k', '525k', '920k', '779k', '853k', '720k', '713k',
       '772k', '318k', '58k', '241k', '196k', '857k', '51k', '953k',
       '865k', '251k', '930k', '540k', '313k', '746k', '203k', '26k',
       '314k', '79k', '239k', '371k', '220k', '730k', '756k', '91k',
       '293k', '17k', '74k', '14k', '317k', '78k', '924k', '902k', '818k',
       '81k', '939k', '169k', '45k', '475k', '965k', '90M', '545k', '61k',
       '283k', '655k', '714k', '93k', '872k', '121k', '322k', '1.0M',
       '976k', '172k', '238k', '549k', '206k', '954k', '444k', '717k',
       '210k', '609k', '308k', '705k', '306k', '904k', '473k', '175k',
       '350k', '383k', '454k', '421k', '70k', '812k', '442k', '842k',
       '417k', '412k', '459k', '478k', '335k', '782k', '721k', '430k',
       '429k', '192k', '200k', '460k', '728k', '496k', '816k', '414k',
       '506k', '887k', '613k', '243k', '569k', '778k', '683k', '592k',
       '319k', '186k', '840k', '647k', '191k', '373k', '437k', '598k',
       '716k', '585k', '982k', '222k', '219k', '55k', '948k', '323k',
       '691k', '511k', '951k', '963k', '25k', '554k', '351k', '27k',
       '82k', '208k', '913k', '514k', '551k', '29k', '103k', '898k',
       '743k', '116k', '153k', '209k', '353k', '499k', '173k', '597k',
       '809k', '122k', '411k', '400k', '801k', '787k', '237k', '50k',
       '643k', '986k', '97k', '516k', '837k', '780k', '961k', '269k',
       '20k', '498k', '600k', '749k', '642k', '881k', '72k', '656k',
       '601k', '221k', '228k', '108k', '940k', '176k', '33k', '663k',
       '34k', '942k', '259k', '164k', '458k', '245k', '629k', '28k',
       '288k', '775k', '785k', '636k', '916k', '994k', '309k', '485k',
       '914k', '903k', '608k', '500k', '54k', '562k', '847k', '957k',
       '688k', '811k', '270k', '48k', '329k', '523k', '921k', '874k',
       '981k', '784k', '280k', '24k', '518k', '754k', '892k', '154k',
       '860k', '364k', '387k', '626k', '161k', '879k', '39k', '970k',
       '170k', '141k', '160k', '144k', '143k', '190k', '376k', '193k',
       '246k', '73k', '658k', '992k', '253k', '420k', '404k', '470k',
       '226k', '240k', '89k', '234k', '257k', '861k', '467k', '157k',
       '44k', '676k', '67k', '552k', '885k', '1020k', '582k', '619k'],
      dtype=object)

In [ ]:
#Convert all size to KB so Each M have to Multiply with 1024
#Removing "M", Changing Size To KB
playstore_df3['Size'] = playstore_df3['Size'].map(
    lambda value :
        str(int(float(value.rstrip('M')) * 1024)) if value[-1] == 'M' else value
)

# Removing "k"
playstore_df3['Size'] = playstore_df3['Size'].map(
    lambda value :
        str(value.rstrip('k')) if value[-1] == 'k' else value
)

# Setting "Varies with device" to NaN
playstore_df3['Size'] = playstore_df3['Size'].map(
    lambda value :
        np.nan if value == 'Varies with device' else value
)

In [ ]:
playstore_df3["Size"].unique()

array(['19456', '8908', '25600', '2867', '5734', '29696', '33792', '3174',
       '28672', '12288', '20480', '21504', '37888', '2764', '5632',
       '17408', '39936', '31744', '14336', '4300', '23552', '6144',
       '6246', '4710', '9420', '5324', '11264', nan, '9625', '15360',
       '10240', '1228', '24576', '26624', '8192', '8089', '57344',
       '58368', '35840', '55296', '201', '3686', '5836', '8806', '2457',
       '27648', '2560', '7168', '16384', '3481', '9113', '3993', '2969',
       '38912', '32768', '5529', '18432', '1126', '2252', '4608', '10035',
       '53248', '9216', '6860', '30720', '2662', '7270', '3788', '22528',
       '7577', '6553', '3276', '8396', '10137', '5017', '9728', '5120',
       '6041', '13312', '74752', '6963', '3584', '4096', '2355', '7372',
       '2150', '43008', '7475', '9318', '56320', '23', '6656', '1536',
       '7680', '52224', '41984', '49152', '8704', '47104', '8499', '4403',
       '4812', '3379', '40960', '7987', '9011', '6758', '5222', '62464',
       '8601', '118', '45056', '695', '1638', '18', '54272', '6348',
       '3072', '5939', '3891', '9830', '46080', '64512', '50176', '78848',
       '4505', '4915', '71680', '7065', '9523', '8294', '36864', '86016',
       '99328', '2048', '1945', '5427', '48128', '556', '526', '77824',
       '1843', '7782', '9932', '79872', '73728', '44032', '7884', '6451',
       '334', '1433', '34816', '95232', '66560', '102400', '51200',
       '69632', '80896', '65536', '68608', '61440', '60416', '96256',
       '59392', '232', '101376', '624', '97280', '8.5', '41', '292', '11',
       '81920', '1740', '70656', '72704', '63488', '100352', '87040',
       '88064', '83968', '82944', '98304', '93184', '84992', '89088',
       '67584', '76800', '94208', '704', '862', '899', '378', '266',
       '375', '75776', '1331', '975', '980', '4198', '91136', '90112',
       '696', '544', '525', '920', '779', '853', '720', '713', '772',
       '318', '58', '241', '196', '857', '51', '953', '865', '251', '930',
       '540', '313', '746', '203', '26', '314', '79', '239', '371', '220',
       '730', '756', '91', '293', '17', '74', '14', '317', '78', '924',
       '902', '818', '81', '939', '169', '45', '475', '965', '92160',
       '545', '61', '283', '655', '714', '93', '872', '121', '322',
       '1024', '976', '172', '238', '549', '206', '954', '444', '717',
       '210', '609', '308', '705', '306', '904', '473', '175', '350',
       '383', '454', '421', '70', '812', '442', '842', '417', '412',
       '459', '478', '335', '782', '721', '430', '429', '192', '200',
       '460', '728', '496', '816', '414', '506', '887', '613', '243',
       '569', '778', '683', '592', '319', '186', '840', '647', '191',
       '373', '437', '598', '716', '585', '982', '222', '219', '55',
       '948', '323', '691', '511', '951', '963', '25', '554', '351', '27',
       '82', '208', '913', '514', '551', '29', '103', '898', '743', '116',
       '153', '209', '353', '499', '173', '597', '809', '122', '411',
       '400', '801', '787', '237', '50', '643', '986', '97', '516', '837',
       '780', '961', '269', '20', '498', '600', '749', '642', '881', '72',
       '656', '601', '221', '228', '108', '940', '176', '33', '663', '34',
       '942', '259', '164', '458', '245', '629', '28', '288', '775',
       '785', '636', '916', '994', '309', '485', '914', '903', '608',
       '500', '54', '562', '847', '957', '688', '811', '270', '48', '329',
       '523', '921', '874', '981', '784', '280', '24', '518', '754',
       '892', '154', '860', '364', '387', '626', '161', '879', '39',
       '970', '170', '141', '160', '144', '143', '190', '376', '193',
       '246', '73', '658', '992', '253', '420', '404', '470', '226',
       '240', '89', '234', '257', '861', '467', '157', '44', '676', '67',
       '552', '885', '1020', '582', '619'], dtype=object)

In [ ]:
playstore_df3['Size']=playstore_df3['Size'].astype('float')

In [ ]:
playstore_df3['Size'].replace([np.nan], playstore_df3['Size'].median(), inplace=True)

In [ ]:
playstore_df3['Size'].isnull().sum()

0

**Price Columns Operation**

In [ ]:
playstore_df3['Price'].unique()

array(['0', '4.99', '3.99', '1.49', '2.99', '7.99', '3.49', '1.99',
       '5.99', '6.99', '9.99', '7.49', '0.99', '9.00', '5.49', '10.00',
       '11.99', '79.99', '16.99', '14.99', '1.00', '29.99', '2.49',
       '24.99', '10.99', '1.50', '19.99', '15.99', '33.99', '74.99',
       '39.99', '4.49', '1.70', '8.99', '2.00', '3.88', '25.99', '399.99',
       '17.99', '400.00', '3.02', '1.76', '4.84', '4.77', '1.61', '2.50',
       '1.59', '6.49', '1.29', '5.00', '13.99', '299.99', '379.99',
       '37.99', '18.99', '389.99', '19.90', '8.49', '1.75', '14.00',
       '4.85', '46.99', '109.99', '3.95', '154.99', '3.08', '2.59',
       '4.80', '1.96', '19.40', '3.90', '4.59', '15.46', '3.04', '12.99',
       '4.29', '2.60', '3.28', '4.60', '28.99', '2.95', '2.90', '1.97',
       '200.00', '89.99', '2.56', '30.99', '3.61', '394.99', '1.26',
       '1.20', '1.04'], dtype=object)

In [ ]:
playstore_df3['Price'] = playstore_df3['Price'].astype('float64')
playstore_df2['Price'].dtype

dtype('O')

In [ ]:
playstore_df3['Price'] = playstore_df3['Price'].apply(pd.to_numeric, errors='coerce')
playstore_df2['Price'].dtype

dtype('O')

**Content Rating Column Operation**

In [ ]:
playstore_df3['Content Rating'].value_counts()

Everyone          7899
Teen              1035
Mature 17          392
Everyone 10        322
Adults only 18       3
Unrated              2
Name: Content Rating, dtype: int64

In [ ]:
playstore_df3[playstore_df3['Content Rating'] == 'Unrated']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
7312,Best CG Photography,FAMILY,4.3,1,2560.0,500,Free,0.0,Unrated,Entertainment,June 24 2015,5.2,3.0 and up
8266,DC Universe Online Map,TOOLS,4.1,1186,6553.0,50000,Free,0.0,Unrated,Tools,February 27 2012,1.3,2.3.3 and up

In [ ]:
playstore_df3['Content Rating'].isnull().sum()

0

**Android Ver Column Operation**

In [ ]:
count_AndroidVer=pd.value_counts(playstore_df3["Android Ver"], sort=True)
count_AndroidVer

4.1 and up            2203
4.0.3 and up          1394
4.0 and up            1286
Varies with device     989
4.4 and up             818
2.3 and up             614
5.0 and up             511
4.2 and up             371
2.3.3 and up           273
2.2 and up             239
3.0 and up             229
4.3 and up             221
2.1 and up             133
1.6 and up             116
6.0 and up              54
7.0 and up              42
3.2 and up              36
2.0 and up              32
5.1 and up              22
1.5 and up              20
4.4W and up             11
3.1 and up              10
2.0.1 and up             7
8.0 and up               6
7.1 and up               3
4.0.3 - 7.1.1            2
5.0 - 8.0                2
1.0 and up               2
7.0 - 7.1.1              1
4.1 - 7.1.1              1
5.0 - 6.0                1
2.2 - 7.1.1              1
5.0 - 7.1.1              1
Name: Android Ver, dtype: int64

**Last Updated Column Operation**

In [ ]:
playstore_df3['Last Updated'] = pd.to_datetime(playstore_df3['Last Updated'])
playstore_df3['Last Updated']

0       2018-01-07
2       2018-08-01
3       2018-06-08
4       2018-06-20
5       2017-03-26
           ...
10836   2017-07-25
10837   2018-07-06
10838   2017-01-20
10839   2015-01-19
10840   2018-07-25
Name: Last Updated, Length: 9653, dtype: datetime64[ns]

In [ ]:
playstore_df3['LastUpdated_Day']=playstore_df3['Last Updated'].dt.day
playstore_df3['LastUpdated_Month']=playstore_df3['Last Updated'].dt.month
playstore_df3['LastUpdated_Year']=playstore_df3['Last Updated'].dt.year

In [ ]:
playstore_df3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9653 entries, 0 to 10840
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   App                9653 non-null   object
 1   Category           9653 non-null   object
 2   Rating             9653 non-null   float64
 3   Reviews            9653 non-null   int64
 4   Size               9653 non-null   float64
 5   Installs           9653 non-null   int64
 6   Type               9653 non-null   object
 7   Price              9653 non-null   float64
 8   Content Rating     9653 non-null   object
 9   Genres             9652 non-null   object
 10  Last Updated       9653 non-null   datetime64[ns]
 11  Current Ver        9645 non-null   object
 12  Android Ver        9651 non-null   object
 13  LastUpdated_Day    9653 non-null   int64
 14  LastUpdated_Month  9653 non-null   int64
 15  LastUpdated_Year   9653 non-null   int64
dtypes: datetime64[ns](1), float64(3), int64(5), object(7)
memory usage: 1.5+ MB

**Seperate Numerical And Categorical Data**

In [ ]:
num_dataf=[col for col in playstore_df3.columns if playstore_df3[col].dtype!='O']
num_dataf

['Rating',
 'Reviews',
 'Size',
 'Installs',
 'Price',
 'Last Updated',
 'LastUpdated_Day',
 'LastUpdated_Month',
 'LastUpdated_Year']

In [ ]:
num_data=playstore_df3[num_dataf]
num_data

,Rating,Reviews,Size,Installs,Price,Last Updated,LastUpdated_Day,LastUpdated_Month,LastUpdated_Year
0,4.1,159,19456.0,10000,0.0,2018-01-07,7,1,2018
2,4.7,87510,8908.0,5000000,0.0,2018-08-01,1,8,2018
3,4.5,215644,25600.0,50000000,0.0,2018-06-08,8,6,2018
4,4.3,967,2867.0,100000,0.0,2018-06-20,20,6,2018
5,4.4,167,5734.0,50000,0.0,2017-03-26,26,3,2017
...,...,...,...,...,...,...,...,...,...
10836,4.5,38,54272.0,5000,0.0,2017-07-25,25,7,2017
10837,5.0,4,3686.0,100,0.0,2018-07-06,6,7,2018
10838,4.3,3,9728.0,1000,0.0,2017-01-20,20,1,2017
10839,4.5,114,12288.0,1000,0.0,2015-01-19,19,1,2015
10840,4.5,398307,19456.0,10000000,0.0,2018-07-25,25,7,2018

In [ ]:
#For categorical Data
cat_dataf=[col for col in playstore_df3.columns if playstore_df3[col].dtype=='O']
cat_dataf

['App',
 'Category',
 'Type',
 'Content Rating',
 'Genres',
 'Current Ver',
 'Android Ver']

In [ ]:
cat_data=playstore_df3[cat_dataf]
cat_data

,App,Category,Type,Content Rating,Genres,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,Free,Everyone,Art & Design,1.0.0,4.0.3 and up
2,U Launcher Lite – FREE Live Cool Themes Hide Apps,ART_AND_DESIGN,Free,Everyone,Art & Design,1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,Free,Teen,Art & Design,Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,Free,Everyone,Art & Design;Creativity,1.1,4.4 and up
5,Paper flowers instructions,ART_AND_DESIGN,Free,Everyone,Art & Design,1.0,2.3 and up
...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,Free,Everyone,Education,1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,Free,Everyone,Education,1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,Free,Everyone,Medical,1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,Free,Mature 17,Books & Reference,Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,Free,Everyone,Lifestyle,Varies with device,Varies with device